### ISSUE TITLE
CT May not have completed all tests

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tandem#181]
```
tandem : top-level-unit-tests : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588238954208/tandem/tandem-tests.html
0 out of 0 tests passed. 0 failed.

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 4/30/2020, 3:29:14 AM

----------------------------------

tandem : top-level-unit-tests : require.js?brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588238954208/tandem/tandem-tests.html?brand=phet-io
0 out of 0 tests passed. 0 failed.

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 4/30/2020, 3:29:14 AM

----------------------------------

tandem : top-level-unit-tests : require.js?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588238954208/tandem/tandem-tests.html?ea
0 out of 0 tests passed. 0 failed.

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 4/30/2020, 3:29:14 AM

----------------------------------

tandem : top-level-unit-tests : require.js?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588238954208/tandem/tandem-tests.html?ea&brand=phet-io
0 out of 0 tests passed. 0 failed.

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 4/30/2020, 3:29:14 AM

```

**Comment by zepumph** [comment]
https://github.com/phetsims/aqua/issues/89

**Comment by zepumph** [comment]
Fixed above. 

@jonathanolson, is there a reason why this is showing up on CT as incomplete? By best guess is that this is because of an uncaught error, but I would have thought that CT would handle that case? 

When I run this locally before the fix I get this error:

```

Source: | TypeError: Cannot read property 'sim' of undefined     at PhetioGroup.createIndexedElement (http://localhost:8080/tandem/js/PhetioGroup.js:237:22)     at PhetioGroup.createNextElement (http://localhost:8080/tandem/js/PhetioGroup.js:210:17)     at Object.<anonymous> (http://localhost:8080/tandem/js/PhetioGroupTests.js:41:27)     at runTest (http://localhost:8080/sherpa/lib/qunit-2.4.1.js:1478:30)     at Test.run (http://localhost:8080/sherpa/lib/qunit-2.4.1.js:1464:6)     at http://localhost:8080/sherpa/lib/qunit-2.4.1.js:1670:12     at Object.advance (http://localhost:8080/sherpa/lib/qunit-2.4.1.js:1116:26)     at begin (http://localhost:8080/sherpa/lib/qunit-2.4.1.js:2937:20)     at http://localhost:8080/sherpa/lib/qunit-2.4.1.js:2897:6
-- | --

```

Is there an open issue to get CT to report uncaught qunit unit test errors?

**Comment by jonathanolson** [comment]
I'll look into the catching of uncaught errors.

Current state of undone tests are the light gray:

![image](https://user-images.githubusercontent.com/480878/111676819-2f40c800-87e4-11eb-8ce3-7f7dd0932a9d.png)

Note that this HID the failure of https://github.com/phetsims/scenery/issues/1183

**Comment by zepumph** [comment]
I just spent all afternoon fuzzing GFL state wrapper, and there were no issues. I also was curious if it had to do with phetLibs being needed, but I didn't see anything suspicious.

**Comment by jonathanolson** [comment]
Almost all tests were run in the burned-in snapshots. Every single test has run in the last week. I believe this is fixed, closing.
