### ISSUE TITLE
CT depth cannot be negative

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tandem#225]
Several sims with these errors
```
atomic-interactions : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/studio/?sim=atomic-interactions&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22atomic-interactions%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1604552995692%22%2C%22timestamp%22%3A1604553771753%7D
Uncaught Error: Uncaught Error: Assertion failed: depth cannot be negative
Error: Assertion failed: depth cannot be negative
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/assert/js/assert.js:22:13)
at DataStream.popNonPlaybackable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/phet-io/js/dataStream.js:347:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:269:58
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/axon/js/Action.js:225:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:1014:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:1004:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:982:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:922:20
id: Bayes Chrome
Snapshot from 11/4/2020, 10:09:55 PM

----------------------------------

atomic-interactions : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/studio/?sim=atomic-interactions&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22atomic-interactions%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1604552995692%22%2C%22timestamp%22%3A1604565421498%7D
Uncaught Error: Uncaught Error: Assertion failed: depth cannot be negative
Error: Assertion failed: depth cannot be negative
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/assert/js/assert.js:22:13)
at DataStream.popNonPlaybackable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/phet-io/js/dataStream.js:347:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:269:58
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/axon/js/Action.js:225:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:1014:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:1004:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:982:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:922:20
id: Bayes Chrome
Snapshot from 11/4/2020, 10:09:55 PM

----------------------------------

atomic-interactions : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/studio/?sim=atomic-interactions&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22atomic-interactions%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1604552995692%22%2C%22timestamp%22%3A1604576157626%7D
Uncaught Error: Uncaught Error: Assertion failed: depth cannot be negative
Error: Assertion failed: depth cannot be negative
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/assert/js/assert.js:22:13)
at DataStream.popNonPlaybackable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/phet-io/js/dataStream.js:347:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:269:58
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/axon/js/Action.js:225:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:1014:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:1004:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:982:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:922:20
id: Bayes Chrome
Snapshot from 11/4/2020, 10:09:55 PM

----------------------------------

atomic-interactions : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/studio/?sim=atomic-interactions&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22atomic-interactions%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1604552995692%22%2C%22timestamp%22%3A1604587569498%7D
Uncaught Error: Uncaught Error: Assertion failed: depth cannot be negative
Error: Assertion failed: depth cannot be negative
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/assert/js/assert.js:22:13)
at DataStream.popNonPlaybackable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/phet-io/js/dataStream.js:347:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:269:58
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/axon/js/Action.js:225:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:1014:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:1004:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:982:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604552995692/joist/js/Sim.js:922:20
id: Bayes Chrome
Snapshot from 11/4/2020, 10:09:55 PM
```

**Comment by zepumph** [comment]
This is because of https://github.com/phetsims/phet-io-wrappers/issues/371#issuecomment-722069214 made last night. I'm unsure why dataStream isn't pushing the nonPlaybackable for the stepSimulationAction. I'll investigate.

**Comment by zepumph** [comment]
Ahh, because when high frequency events aren't emitted, it short circuits and doesn't push/pop. @samreid, I'd love a quick conversation on this to make sure I head down a good direction.

**Comment by zepumph** [comment]
The above will fix the ct error, but it is really horrid. I'm going to see about something better.

**Comment by zepumph** [comment]
Solved poorly above. Fixed better over in https://github.com/phetsims/phet-io-wrappers/issues/371. CT is fixed. Closing
