### ISSUE TITLE
CT PhetioObject not found

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tandem#227]
Number of sims failing CT with similar issues:
```
build-an-atom : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611639176366/build-an-atom/build-an-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22build-an-atom%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611639176366%22%2C%22timestamp%22%3A1611641682833%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhetioObject not found for buildAnAtom.optionalTandem.firedEmitter
Error: Assertion failed: PhetioObject not found for buildAnAtom.optionalTandem.firedEmitter
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611639176366/assert/js/assert.js:25:13)
at PhetioEngine.assertPhetioObjectFound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611639176366/phet-io/js/phetioEngine.js:345:17)
at PhetioEngine.getPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611639176366/phet-io/js/phetioEngine.js:449:20)
at FireListenerSpecification.test (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611639176366/scenery/js/listeners/FireListenerSpecification.js:51:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611639176366/scenery/js/listeners/FireListener.js:31:75
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611639176366/axon/js/Timer.js:32:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611639176366/axon/js/TinyEmitter.js:71:18)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611639176366/joist/js/Sim.js:1023:25)
id: Bayes Chrome
Snapshot from 1/25/2021, 10:32:56 PM
```

**Comment by samreid** [comment]
Tagging for https://github.com/phetsims/phet-io/issues/1657 and proposed fix committed and testing OK locally, closing.
